sudo: required

language: python

python:
  - 2.7

services:
  - docker

install:
  - echo "do nothing"
  # - cd $TRAVIS_BUILD_DIR
  # - cd src
  # - pip install -r requirements.txt

before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi'

script: 
  - echo "do nothing here"

after_success:
  - cd $TRAVIS_BUILD_DIR
  - cd src
  - docker build -t "chenggangschool/vote:latest" -t "chenggangschool/vote:1.0.$TRAVIS_BUILD_NUMBER" .

deploy:
  provider: script
  skip_cleanup: true
  script: docker push chenggangschool/vote
  on:
    branch: master
